# Generated by Django 4.0.1 on 2024-05-23 09:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('homechallenge_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Todolist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=500)),
                ('status', models.BooleanField(default=False)),
                ('updated_date', models.DateField()),
                ('Project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homechallenge_app.project')),
            ],
        ),
    ]
