# Generated by Django 4.0.1 on 2024-05-23 16:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homechallenge_app', '0003_alter_project_todos'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todolist',
            old_name='Project',
            new_name='project',
        ),
    ]
