# Generated by Django 4.0.1 on 2024-05-25 08:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homechallenge_app', '0006_project_created_by'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Login',
        ),
    ]
